/*
 * LCD_CONFIG.h
 *
 * Created: 11/10/2023 3:06:11 AM
 *  Author: mostafa
 */ 


#ifndef LCD_CONFIG_H_
#define LCD_CONFIG_H_

#define LCD_DATA_PORT PORTA
#define LCD_CONTROL_PORT PORTB


#define LCD_BS 1
#define LCD_RW 2
#define LCD_E 3

#define LCD_CLEAR_DISPLAY_COMMAND 0x01
#define LCD_CLEAR_DISPLAY_COMMAND_DELAY _delay_ms(200)

#define LCD_RETURN_HOME_COMMAND 0x02
#define LCD_RETURN_HOME_COMMAND_DELAY _delay_ms(2)

#define LCD_ENTRY_MODE_COMMAND 0x04
#define LCD_ENTRY_MODE_ID_CURSOR_COMMAND 0x02
#define LCD_ENTRY_MODE_SH_COMMAND 0x01
#define LCD_ENTRY_MODE_COMMAND_DELAY _delay_us(40)


#define LCD_FUNCTION_SET_COMMAND 0x20
#define LCD_FUNCTION_SET_DL_COMMAND 0x10
#define LCD_FUNCTION_SET_N_COMMAND 0x0F
#define LCD_FUNCTION_SET_F_COMMAND 0x08
#define LCD_FUNCTION_SET_COMMAND_DELAY _delay_us(40)


#define LCD_DISPLAY_ON_OFF_CONTROL_COMMAND 0x08
#define LCD_DISPLAY_ON_OFF_CONTROL_D_COMMAND 0x04
#define LCD_DISPLAY_ON_OFF_CONTROL_C_COMMAND 0x02
#define LCD_DISPLAY_ON_OFF_CONTROL_B_COMMAND 0x01

#define LCD_CURSOR_DISPLAY_SHIFT_COMMAND 0x10
#define LCD_CURSOR_DISPLAY_SHIFT_SC_COMMAND 0x08
#define LCD_CURSOR_DISPLAY_SHIFT_RL_COMMAND 0x04
#define LCD_CURSOR_DISPLAY_SHIFT_COMMAND_DELAY _delay_us(40)





#endif /* LCD_CONFIG_H_ */